---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet

inherit_mode:
  merge:
    - Exclude
    - ExcludedMethods

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Layout/ClassStructure:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 80

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/BlockLength:
  Exclude: []
  ExcludedMethods:
    - context
    - describe

Metrics/MethodLength:
  Max: 5
  ExcludedMethods: []
  Exclude: []

Metrics/ParameterLists:
  Max: 4

RSpec/EmptyExampleGroup:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Sorbet:
  Enabled: false
