---
name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'releases'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.1
        env:
          DEFAULT_BRANCH: releases
          ACTIONS_RUNNER_DEBUG: true
